import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const init = new URL('../skills/init/scripts/init.mjs', import.meta.url).pathname;
const config = new URL('../skills/config/scripts/config.mjs', import.meta.url).pathname;

function project() {
  const root = mkdtempSync(join(tmpdir(), 'sw-config-'));
  execFileSync('node', [init, '--root', root, '--tasks', '--areas', 'M=Mobile']);
  return root;
}
const run = (root, ...args) => execFileSync('node', [config, ...args, '--root', root], { encoding: 'utf8' });
const read = (root, path) => readFileSync(join(root, path), 'utf8');

test('setting a model writes all three role files, for that tool only', () => {
  const root = project();
  const out = run(root, 'model', 'plan', 'claude', 'opus');
  assert.match(out, /created {3}\.claude\/agents\/sw-planner\.md\ncreated {3}\.claude\/agents\/sw-implementer\.md\ncreated {3}\.claude\/agents\/sw-reviewer\.md/);

  const planner = read(root, '.claude/agents/sw-planner.md');
  const implementer = read(root, '.claude/agents/sw-implementer.md');
  const reviewer = read(root, '.claude/agents/sw-reviewer.md');
  assert.match(planner, /^---\nname: sw-planner\ndescription: [^\n]+\nmodel: opus\n---\n\n<!-- Generated by sw:config/);
  assert.match(planner, /# Planner/);
  assert.doesNotMatch(implementer, /^model:/m, 'a role without a model inherits the tool default');
  assert.match(reviewer, /You change no file in the repository/);
  assert.match(reviewer, /^tools: Read, Grep, Glob, Bash$/m, 'the reviewer gets reading, searching and shell tools only');
  assert.doesNotMatch(planner, /^tools:/m, 'the planner keeps the tool default');
  assert.doesNotMatch(implementer, /^tools:/m, 'the implementer keeps the tool default');
  assert.ok(!existsSync(join(root, '.codex')));
  assert.ok(!existsSync(join(root, '.github')));
});

test('codex and copilot get their own formats', () => {
  const root = project();
  run(root, 'model', 'review', 'codex', 'gpt-6');
  run(root, 'model', 'implement', 'copilot', 'gpt-6');

  const reviewer = read(root, '.codex/agents/sw-reviewer.toml');
  assert.match(reviewer, /^# Generated by sw:config[^\n]*\nname = "sw_reviewer"\ndescription = "[^"\n]+"\nmodel = "gpt-6"\ndeveloper_instructions = '''\n# Reviewer/);
  assert.doesNotMatch(read(root, '.codex/agents/sw-implementer.toml'), /^model = /m);
  assert.match(read(root, '.github/agents/sw-implementer.agent.md'), /\nmodel: gpt-6\n---/);
  assert.doesNotMatch(reviewer, /^tools/m, 'the codex reviewer carries no tools list');
  assert.doesNotMatch(read(root, '.github/agents/sw-reviewer.agent.md'), /^tools/m, 'the copilot reviewer carries no tools list');
});

test('unset, areas and show; sw:init keeps models and tools on re-run', () => {
  const root = project();
  run(root, 'model', 'plan', 'claude', 'opus');
  run(root, 'model', 'review', 'claude', 'opus');
  run(root, 'model', 'plan', 'claude', '--unset');
  assert.doesNotMatch(read(root, '.claude/agents/sw-planner.md'), /^model:/m);
  assert.match(read(root, '.claude/agents/sw-reviewer.md'), /\ntools: Read, Grep, Glob, Bash\nmodel: opus\n---/, 'tools come before model in the frontmatter');
  run(root, 'areas', 'B=Backend');
  execFileSync('node', [init, '--root', root]);

  const show = run(root, 'show');
  assert.match(show, /areas: M=Mobile, B=Backend/);
  assert.match(show, /plan: claude=default/);
  assert.match(show, /review: claude=opus/);
  assert.match(show, /agent files for: claude/);
});

test('a config written before the review role existed still works', () => {
  const root = project();
  const path = join(root, 'docs/.sw/config.json');
  const old = JSON.parse(read(root, 'docs/.sw/config.json'));
  old.models = { plan: { claude: 'opus' }, implement: {} };
  writeFileSync(path, JSON.stringify(old));
  assert.match(run(root, 'show'), /plan: claude=opus[^\n]*\nimplement: [^\n]*\nreview: claude=default/);
});

test('usage errors exit with 2 and say why', () => {
  const root = project();
  const badTool = spawnSync('node', [config, 'model', 'plan', 'cursor', 'x', '--root', root], { encoding: 'utf8' });
  assert.equal(badTool.status, 2);
  assert.match(badTool.stderr, /usage: config\.mjs model <plan\|implement\|review>/);
  const noVault = spawnSync('node', [config, 'show', '--root', mkdtempSync(join(tmpdir(), 'sw-empty-'))], { encoding: 'utf8' });
  assert.equal(noVault.status, 2);
  assert.match(noVault.stderr, /run sw:init first/);
});
