#!/usr/bin/env node
// Reads and changes docs/.sw/config.json, and writes the planner, implementer and reviewer agent files.
// A coding tool binds a model to an agent definition, not to a running session, so choosing a
// model for a role means writing that role's agent file for that tool.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Each role file lives in the skill that dispatches it: `plan/assets/planner.md`,
// `implement/assets/implementer.md` and `reviewer.md`. This script finds them as sibling skill
// folders of its own, the way init.mjs finds the skills it copies: under `skills/` of a checkout
// or a plugin the folders carry bare names; in an agent's skills folder, where this skill is itself
// an `sw-<name>` copy, its siblings carry the same prefix. A linked script runs at its real path.
const SKILL_DIR = join(dirname(fileURLToPath(import.meta.url)), '..');
const SKILLS_ROOT = dirname(SKILL_DIR);
const INSTALLED_PREFIX = 'sw-';
const SKILL_PREFIX = basename(SKILL_DIR).startsWith(INSTALLED_PREFIX) ? INSTALLED_PREFIX : '';
const roleFile = ({ skill, file }) => join(SKILLS_ROOT, SKILL_PREFIX + skill, 'assets', file);

const GENERATED = 'Generated by sw:config from docs/.sw/config.json. Change models with sw:config, not here.';
const AREA_ID = /^[A-Za-z][A-Za-z0-9]*$/;

// `tools` lists, per tool, what the agent may use; only tools whose field is known carry one.
// The reviewer gets reading, searching and the shell, none of the editing tools.
const ROLES = {
  plan: {
    name: 'sw-planner',
    instructions: { skill: 'plan', file: 'planner.md' },
    description: 'Writes the plan file for one Superwiki task. Use from sw:plan.',
  },
  implement: {
    name: 'sw-implementer',
    instructions: { skill: 'implement', file: 'implementer.md' },
    description: 'Implements one Superwiki task from its task and plan files. Use from sw:implement.',
  },
  review: {
    name: 'sw-reviewer',
    instructions: { skill: 'implement', file: 'reviewer.md' },
    description: 'Reviews the implementation of one Superwiki task from a clean context. Use from sw:implement and sw:review.',
    tools: { claude: 'Read, Grep, Glob, Bash' },
  },
};

// How each tool wants an agent defined: where the file goes and what it looks like.
const TOOLS = {
  claude: {
    path: role => `.claude/agents/${role.name}.md`,
    render: (role, body, model) => markdownAgent(role, body, model, role.tools?.claude),
  },
  codex: {
    path: role => `.codex/agents/${role.name}.toml`,
    render: (role, body, model) => [
      `# ${GENERATED}`,
      `name = "${role.name.replace(/-/g, '_')}"`,
      `description = ${JSON.stringify(role.description)}`,
      ...(model ? [`model = ${JSON.stringify(model)}`] : []),
      // TOML literal strings cannot contain three single quotes in a row.
      `developer_instructions = '''\n${body.replace(/'''/g, "' ' '")}\n'''`,
      '',
    ].join('\n'),
  },
  copilot: {
    path: role => `.github/agents/${role.name}.agent.md`,
    render: (role, body, model) => markdownAgent(role, body, model),
  },
};

function markdownAgent(role, body, model, tools) {
  const frontmatter = [
    `name: ${role.name}`,
    `description: ${role.description}`,
    ...(tools ? [`tools: ${tools}`] : []),
    ...(model ? [`model: ${model}`] : []),
  ];
  return `---\n${frontmatter.join('\n')}\n---\n\n<!-- ${GENERATED} -->\n\n${body}\n`;
}

const TOOL_NAMES = Object.keys(TOOLS);
const ROLE_NAMES = Object.keys(ROLES);

const HELP = `config.mjs <command> [--root <dir>]

  show                                   print the configuration
  model <${ROLE_NAMES.join('|')}> <tool> <model>  set the model a tool uses for a role (tool: ${TOOL_NAMES.join(', ')})
  model <${ROLE_NAMES.join('|')}> <tool> --unset  go back to the tool's default model
  areas "M=Mobile,B=Backend"             add or rename task areas (existing areas are never removed)
  sync [--tools claude,codex]            (re)write agent files for the given tools, or for every configured tool`;

class UsageError extends Error {}

function parseArgs(argv) {
  const args = [];
  let root = '.';
  let tools = null;
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--root') root = argv[++i] ?? '.';
    else if (argv[i] === '--tools') tools = (argv[++i] ?? '').split(',').map(s => s.trim()).filter(Boolean);
    else args.push(argv[i]);
  }
  return { command: args[0], args: args.slice(1), root: resolve(root), tools };
}

function loadConfig(root) {
  const path = join(root, 'docs/.sw/config.json');
  if (!existsSync(path)) throw new UsageError('no docs/.sw/config.json here; run sw:init first');
  const config = JSON.parse(readFileSync(path, 'utf8'));
  config.models = { ...Object.fromEntries(ROLE_NAMES.map(role => [role, {}])), ...config.models };
  config.tools ??= [];
  return { config, save: () => writeFileSync(path, JSON.stringify(config, null, 2) + '\n') };
}

const formatAreas = areas => Object.entries(areas).map(([id, name]) => `${id}=${name}`).join(', ');

// Writes a generated file and says what happened to it, judged by content.
function writeGenerated(root, relPath, content) {
  const path = join(root, relPath);
  const before = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (before !== content) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
  }
  const state = before === null ? 'created  ' : before === content ? 'unchanged' : 'updated  ';
  console.log(`${state} ${relPath}`);
}

function writeAgentFiles(root, config, toolNames) {
  for (const [roleName, role] of Object.entries(ROLES)) {
    const path = roleFile(role.instructions);
    if (!existsSync(path)) throw new Error(`the role file for ${roleName} is missing: ${path}`);
    const body = readFileSync(path, 'utf8').trim();
    for (const toolName of toolNames) {
      const tool = TOOLS[toolName];
      writeGenerated(root, tool.path(role), tool.render(role, body, config.models[roleName][toolName]));
    }
  }
}

function rememberTools(config, toolNames) {
  for (const name of toolNames) if (!config.tools.includes(name)) config.tools.push(name);
}

const COMMANDS = {
  show({ config }) {
    console.log(`tasks: ${config.tasks ? 'on' : 'off'}`);
    if (config.tasks) console.log(`areas: ${formatAreas(config.areas)}`);
    for (const role of ROLE_NAMES) {
      console.log(`${role}: ${TOOL_NAMES.map(tool => `${tool}=${config.models[role][tool] || 'default'}`).join('  ')}`);
    }
    console.log(`agent files for: ${config.tools.join(', ') || 'none'}`);
  },

  model({ root, config, save, args }) {
    const [role, tool, model] = args;
    if (!ROLES[role] || !TOOLS[tool] || !model) {
      throw new UsageError(`usage: config.mjs model <${ROLE_NAMES.join('|')}> <${TOOL_NAMES.join('|')}> <model|--unset>`);
    }
    if (model === '--unset') delete config.models[role][tool];
    else config.models[role][tool] = model;
    rememberTools(config, [tool]);
    save();
    writeAgentFiles(root, config, [tool]);
  },

  areas({ config, save, args }) {
    if (!config.tasks) throw new UsageError('the task module is off; run sw:init with --tasks first');
    for (const pair of (args[0] || '').split(',').map(s => s.trim()).filter(Boolean)) {
      const [id, ...nameParts] = pair.split('=');
      if (!AREA_ID.test(id)) throw new UsageError(`bad area id "${id}"`);
      config.areas[id] = nameParts.join('=').trim() || config.areas[id] || id;
    }
    save();
    console.log(`areas: ${formatAreas(config.areas)}`);
  },

  sync({ root, config, save, tools }) {
    const toolNames = tools ?? config.tools;
    const unknown = toolNames.filter(name => !TOOLS[name]);
    if (unknown.length) throw new UsageError(`unknown tool: ${unknown.join(', ')}`);
    if (!toolNames.length) throw new UsageError(`no tools configured; pass --tools ${TOOL_NAMES.join(',')}`);
    rememberTools(config, toolNames);
    save();
    writeAgentFiles(root, config, toolNames);
  },
};

function main(argv) {
  const { command, args, root, tools } = parseArgs(argv);
  if (!command || command === 'help' || command === '--help') {
    console.log(HELP);
    return 0;
  }
  try {
    const run = COMMANDS[command];
    if (!run) throw new UsageError(`unknown command ${command}\n\n${HELP}`);
    run({ root, args, tools, ...loadConfig(root) });
    return 0;
  } catch (error) {
    if (!(error instanceof UsageError)) throw error;
    console.error(error.message);
    return 2;
  }
}

process.exitCode = main(process.argv.slice(2));
