// Bundles src/ into the files sw-init copies into a project:
//   skills/sw-init/assets/sw.mjs       core + CLI, one dependency-free file
//   skills/sw-init/assets/viewer.html  viewer with the core inlined
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const assets = join(root, 'skills/sw-init/assets');
const read = p => readFileSync(join(root, p), 'utf8');
mkdirSync(assets, { recursive: true });

const core = read('src/core.js');
const cli = read('src/cli.js').replace(/^import .* from '\.\/core\.js';\n/m, '');
writeFileSync(join(assets, 'sw.mjs'), `#!/usr/bin/env node\n// Generated by scripts/build.mjs from src/core.js and src/cli.js. Do not edit.\n${core}\n${cli}`);
console.log('built skills/sw-init/assets/sw.mjs');

if (existsSync(join(root, 'src/viewer.html'))) {
  const marker = '/*__SW_CORE__*/';
  const html = read('src/viewer.html');
  if (!html.includes(marker)) throw new Error(`src/viewer.html has no ${marker} marker`);
  // The viewer script is not a module, so the core's exports become plain globals.
  writeFileSync(join(assets, 'viewer.html'), html.replace(marker, () => core.replace(/^export /gm, '')));
  console.log('built skills/sw-init/assets/viewer.html');
}
