// Bundles src/ into the files sw-init copies into a project:
//   skills/sw-init/assets/sw.mjs       the CLI and everything it uses, one dependency-free file
//   skills/sw-init/assets/viewer.html  viewer with the core inlined
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const assets = join(root, 'skills/sw-init/assets');
const read = p => readFileSync(join(root, p), 'utf8');
mkdirSync(assets, { recursive: true });

// In dependency order: a module comes after the modules it imports from.
const CLI_MODULES = ['src/core.js', 'src/sessions.js', 'src/stats.js', 'src/doctor.js', 'src/cli.js'];

// Joins ES modules into one file. Imports between the modules are dropped, since their code is in
// the bundle; imports from Node are merged, since a file can import a name only once.
function bundle(paths) {
  const fromNode = new Map();
  const bodies = paths.map(path =>
    read(path).replace(/^import \{ ([^}]+) \} from '([^']+)';\n/gm, (_, names, source) => {
      if (source.startsWith('node:')) {
        if (!fromNode.has(source)) fromNode.set(source, new Set());
        for (const name of names.split(',')) fromNode.get(source).add(name.trim());
      }
      return '';
    }),
  );
  const leftover = bodies.join('\n').match(/^import .*$/m);
  if (leftover) throw new Error(`cannot bundle this import: ${leftover[0]}`);
  const imports = [...fromNode].map(([source, names]) => `import { ${[...names].sort().join(', ')} } from '${source}';`);
  return [...imports, ...bodies].join('\n');
}

const cliPath = join(assets, 'sw.mjs');
writeFileSync(cliPath, `#!/usr/bin/env node\n// Generated by scripts/build.mjs from ${CLI_MODULES.join(', ')}. Do not edit.\n${bundle(CLI_MODULES)}`);
// Two modules declaring the same name only fails once they share a file.
execFileSync(process.execPath, ['--check', cliPath], { stdio: 'inherit' });
console.log('built skills/sw-init/assets/sw.mjs');

if (existsSync(join(root, 'src/viewer.html'))) {
  const marker = '/*__SW_CORE__*/';
  const html = read('src/viewer.html');
  if (!html.includes(marker)) throw new Error(`src/viewer.html has no ${marker} marker`);
  // The viewer script is not a module, so the core's exports become plain globals.
  const core = read('src/core.js');
  writeFileSync(join(assets, 'viewer.html'), html.replace(marker, () => core.replace(/^export /gm, '')));
  console.log('built skills/sw-init/assets/viewer.html');
}
