#!/usr/bin/env node
// Reads and changes docs/.sw/config.json, and writes the planner and implementer agent
// definitions each tool needs. In all three tools a model is bound to an agent file, not chosen at run time.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const assets = join(dirname(fileURLToPath(import.meta.url)), '..', 'assets');
const TOOLS = ['claude', 'codex', 'copilot'];
const ROLES = {
  plan: { name: 'sw-planner', file: 'planner.md', readOnly: true, description: 'Writes the plan for one Superwiki task. Read-only. Use from sw-plan.' },
  implement: { name: 'sw-implementer', file: 'implementer.md', readOnly: false, description: 'Implements one Superwiki task from its task and plan files. Use from sw-implement.' },
};
const HELP = `config.mjs <command> [--root <dir>]

  show                                   print the configuration
  model <plan|implement> <tool> <model>  set the model a tool uses for a role (tool: ${TOOLS.join(', ')})
  model <plan|implement> <tool> --unset  go back to the tool's default model
  areas "M=Mobile,B=Backend"             add or rename task areas (existing areas are never removed)
  sync [--tools claude,codex]            (re)write agent files for the given tools, or for every configured tool`;

const argv = process.argv.slice(2);
const ri = argv.indexOf('--root');
const root = resolve(ri >= 0 ? argv[ri + 1] : '.');
if (ri >= 0) argv.splice(ri, 2);
const [cmd, ...rest] = argv;
const fail = msg => { console.error(msg); process.exit(2); };
if (!cmd || cmd === '--help' || cmd === 'help') { console.log(HELP); process.exit(0); }

const configPath = join(root, 'docs/.sw/config.json');
if (!existsSync(configPath)) fail('no docs/.sw/config.json here; run sw-init first');
const config = JSON.parse(readFileSync(configPath, 'utf8'));
config.models = { plan: {}, implement: {}, ...config.models };
config.tools = config.tools || [];

const put = (rel, content) => {
  const p = join(root, rel);
  const before = existsSync(p) ? readFileSync(p, 'utf8') : null;
  if (before !== content) { mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, content); }
  console.log(`${before === null ? 'created  ' : before === content ? 'unchanged' : 'updated  '} ${rel}`);
};
const header = 'Generated by sw-config from docs/.sw/config.json. Change models with sw-config, not here.';

function sync(tools) {
  for (const [role, r] of Object.entries(ROLES)) {
    const body = readFileSync(join(assets, r.file), 'utf8').trim();
    const model = tool => config.models[role]?.[tool];
    if (tools.includes('claude')) {
      const fm = ['---', `name: ${r.name}`, `description: ${r.description}`];
      if (r.readOnly) fm.push('tools: Read, Grep, Glob');
      if (model('claude')) fm.push(`model: ${model('claude')}`);
      put(`.claude/agents/${r.name}.md`, `${fm.join('\n')}\n---\n\n<!-- ${header} -->\n\n${body}\n`);
    }
    if (tools.includes('codex')) {
      const lines = [`# ${header}`, `name = "${r.name.replace(/-/g, '_')}"`, `description = ${JSON.stringify(r.description)}`];
      if (model('codex')) lines.push(`model = ${JSON.stringify(model('codex'))}`);
      if (r.readOnly) lines.push('sandbox_mode = "read-only"');
      lines.push(`developer_instructions = '''\n${body.replace(/'''/g, "' ' '")}\n'''`);
      put(`.codex/agents/${r.name}.toml`, lines.join('\n') + '\n');
    }
    if (tools.includes('copilot')) {
      const fm = ['---', `name: ${r.name}`, `description: ${r.description}`];
      if (r.readOnly) fm.push('tools: ["read", "search"]');
      if (model('copilot')) fm.push(`model: ${model('copilot')}`);
      put(`.github/agents/${r.name}.agent.md`, `${fm.join('\n')}\n---\n\n<!-- ${header} -->\n\n${body}\n`);
    }
  }
}
const save = () => writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');

if (cmd === 'show') {
  console.log(`tasks: ${config.tasks ? 'on' : 'off'}`);
  if (config.tasks) console.log(`areas: ${Object.entries(config.areas).map(([k, v]) => `${k}=${v}`).join(', ')}`);
  for (const role of Object.keys(ROLES)) {
    console.log(`${role}: ${TOOLS.map(t => `${t}=${config.models[role][t] || 'default'}`).join('  ')}`);
  }
  console.log(`agent files for: ${config.tools.join(', ') || 'none'}`);
} else if (cmd === 'model') {
  const [role, tool, model] = rest;
  if (!ROLES[role] || !TOOLS.includes(tool) || !model) fail(`usage: config.mjs model <plan|implement> <${TOOLS.join('|')}> <model|--unset>`);
  if (model === '--unset') delete config.models[role][tool];
  else config.models[role][tool] = model;
  if (!config.tools.includes(tool)) config.tools.push(tool);
  save();
  sync([tool]);
} else if (cmd === 'areas') {
  if (!config.tasks) fail('the task module is off; run sw-init with --tasks first');
  for (const pair of (rest[0] || '').split(',').map(s => s.trim()).filter(Boolean)) {
    const [id, ...name] = pair.split('=');
    if (!/^[A-Za-z][A-Za-z0-9]*$/.test(id)) fail(`bad area id "${id}"`);
    config.areas[id] = name.join('=').trim() || config.areas[id] || id;
  }
  save();
  console.log(`areas: ${Object.entries(config.areas).map(([k, v]) => `${k}=${v}`).join(', ')}`);
} else if (cmd === 'sync') {
  const ti = rest.indexOf('--tools');
  const tools = ti >= 0 ? rest[ti + 1].split(',').map(s => s.trim()) : config.tools;
  const bad = tools.filter(t => !TOOLS.includes(t));
  if (bad.length) fail(`unknown tool: ${bad.join(', ')}`);
  if (!tools.length) fail('no tools configured; pass --tools claude,codex,copilot');
  for (const t of tools) if (!config.tools.includes(t)) config.tools.push(t);
  save();
  sync(tools);
} else fail(`unknown command ${cmd}\n\n${HELP}`);
